[tool.flake8]
exclude = [
    ".git",
    "__pycache__",
    "venv",
    "env",
    ".venv",
    "build",
    "dist",
    "*.egg-info"
]
ignore = [
    "E203",
    "E266",
    "E501",
    "W503",
    "F403",
    "F401",
    "E402",
    "E302",
    "E305",
    "E722",
    "E731",
    "W291",
    "W293",
    "W391",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D401",
    "N802",
    "N803",
    "N806"
]
max-line-length = 200
max-complexity = 20

[tool.pylint]
disable = [
    "C0103",
    "C0111",
    "C0114",
    "C0115",
    "C0116",
    "R0903",
    "R0913",
    "W0613",
    "W0212"
]

